# Configuration file for the NAS

# some enums still need to be defined and documented

[pipeline]
# population size
population_size = 50
# unsustainable population size
unsustainable_population_size = 500
# number of parents to be selected to mate
num_parents = 20
# types of crossovers and their probabilities
crossovers = {one_point = 0.5, one_point_leaf_biased = 0.3}
# types of mutations and their probabilities
mutations = {node_replacement = 0.1}
# whether to use surrogate
surrogate_enabled = false
# GA objectives to optimize for and their weights (matter only relative to each other)
objectives = {MSE = -1, GIoU = 1, MAP = 1}
# number of epochs to train individuals for
train_epochs = 40
# strategy for down selecting individuals trusted by the surrogate
selection_method_trusted = "NSGA2" # Need to define all enums
# strategy for down selecting individuals untrusted by the surrogate
selection_method_untrusted = "Random" # Need to define all enums
# strategy for selecting parents to mate for overpopulating
selection_method_parents = "NSGA2" # Need to define all enums
# strategy for selecting elite individuals
selection_method_elite_pool = "SPEA2" # Need to define all enums
# max size of elite pool
max_elite_pool = 100
# source of genomes to train the surrogate with each generation 
train_pool_source = "All" 
# source of genomes used to calculate the trust value of the surrogate(s)
trust_pool_source = "ElitePopMix"
# criteria to select best epoch
best_epoch_criteria = ["GIoU", "max"]

[codec]
# method of encoding NN as a genome
genome_encoding_strat = "Tree" # Need to define 
# method of encoding NN for the surrogate
surrogate_encoding_strat = "Graph2Vec"
# number of components weighted together to make the loss for the individual
num_loss_components = 9

[surrogate]
# surrogate models to be used
models = ["MLP", "GRBT", "XGB", "Transformer"]
# method of calculating the trust of a surrogate
trust_calc_strategy = "SPEA2"
# ratio of population to check intersection on
trust_calc_ratio = 0.3

