# Configuration file for the NAS

[pipeline]
# initial population size
initial_population_size = 200
# population size
population_size = 30
# unsustainable population size
unsustainable_population_size = 500
# number of parents to be selected to mate
num_parents = 6
# types of crossovers and their probabilities
crossovers = {one_point = 0.5, one_point_leaf_biased = 0.3}
# types of mutations and their probabilities
mutations = {node_replacement = 0.2, type_fixed_mut = 0.3}
# whether to use surrogate
surrogate_enabled = true
# whether to track average false positives as a metric (backwards compatibility)
track_average_false_positives = false
# GA objectives to optimize for and their weights (matter only relative to each other)
objectives = {ciou_loss = -1, average_precision = 1}
# strategy for down selecting individuals trusted by the surrogate
selection_method_trusted = "NSGA2" # Need to define all enums
# strategy for down selecting individuals untrusted by the surrogate
selection_method_untrusted = "Random" # Need to define all enums
# strategy for selecting parents to mate for overpopulating
selection_method_parents = "NSGA2" # Need to define all enums
# strategy for selecting elite individuals
selection_method_elite_pool = "SPEA2" # Need to define all enums
# max size of elite pool
max_elite_pool = 4
# source of genomes to train the surrogate with each generation 
train_pool_source = "All" 
# source of genomes used to calculate the trust value of the surrogate(s)
trust_pool_source = "ElitePopMix"
# criteria to select best epoch
best_epoch_criteria = ["average_precision", "max"]
# whether to use simulated surrogate injection (SSI)
ssi = true
# number of generations of simulation with surrogate-only
num_gens_ssi = 5
# frequency at which ssi occurs
ssi_freq = 1
# first generation to use SSI
ssi_start_gen = 3
# size of unsustainable population during ssi
ssi_unsustainable_population_size = 2000
# size of sustainable population during ssi
ssi_sustainable_population_size = 500
# whether to use surrogate when calling the final downselect operation on the unsustainable population
surrogate_in_final_downselect = false
# number of parents to select in ssi loop
num_parents_ssi = 20
# percent of individuals submitted for evaluation that should be sourced from ssi
ssi_population_percentage = 0.8


[model]
# number of epochs to train individuals for
train_epochs = 10
# batch size
batch_size = 2
# number of batches in one epoch
batches_per_epoch = 500
# number of target classes in AOT
num_classes = 7
# iou threshold for determining detection
iou_thresh = 0.0
# confidence threshold for filtering predictions
conf_thresh = 0.2
# priority type of iou calculation
iou_type = "ciou"
# min bounding box area in pixels for eiou (=0 if eiou not used)
min_object_area = 0
# number of components weighted together to make the loss for the individual
num_loss_components = 7
# seed for loading train data
train_seed = 0
# seed for loading val data
val_seed = 0

[codec]
# method of encoding NN as a genome
genome_encoding_strat = "Tree" # Need to define 
# method of encoding NN for the surrogate
surrogate_encoding_strat = "String2Vec"

[surrogate]
# surrogate models to be used
models = ["MLP", "KAN"]
# surrogate metrics
surrogate_metrics = ["mse_uw_val_loss", "mse_iou_loss", "mse_giou_loss", "mse_diou_loss", "mse_ciou_loss", "mse_center_loss", "mse_size_loss", "mse_obj_loss", "mse_precision", "mse_recall", "mse_f1_score", "mse_average_precision"]
# optimization directions of the genome metrics
opt_directions = ['min', 'min', 'min', 'min', 'min', 'min', 'min', 'min', 'max', 'max', 'max', 'max']
# number of epochs to train the surrogates for
surrogate_train_epochs = 30
# batch size used in surrogate evaluation
surrogate_batch_size = 16
# method of calculating the trust of a surrogate
trust_calc_strategy = "SPEA2"
# ratio of population to check intersection on
trust_calc_ratio = 0.3
# choose whether to select sub surrogates using trust or mse scores
sub_surrogate_sel_strat = "mse"
# minimum validation set size in number of batches the surrogate should have for it to train
min_batch_in_val_data = 2
# flag that determines whether surrogate 'pretrains' on prev run data
pretrained = true
# folder containing surrogate datasets used in pretraining the model
pretrained_dir = '/storage/ice-shared/vip-vvk/data/AOT/surrogate_dataset'
# flag that determines whether inputs to the surrogate are preprocessed using a VAE
preprocess = true
# batch size to use when training the preprocessor VAE
preprocess_batch_size = 16

[data]
# time in hours the dataset cache is valid for
cache_thresh = 1
# size of the dataset
max_size = 1000

