#!/bin/bash
#SBATCH --job-name=t_evo_5
#SBATCH --nodes=1
#SBATCH -G 1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32GB
#SBATCH --time=08:00:00
#SBATCH --output=/storage/ice-shared/vip-vvk/data/AOT/psomu3/testing_baseline2/testing_baseline/logs/generation_5/evaluation.%A.%a.log
#SBATCH --error=/storage/ice-shared/vip-vvk/data/AOT/psomu3/testing_baseline2/testing_baseline/logs/generation_5/evaluation_error.%A.%a.log
#SBATCH --array=0-29
#SBATCH --constraint="V100-16GB|V100-32GB|L40S|A100-40GB|H100"

module load anaconda3/2023.03
module load cuda/12.1.1
mkdir -p /storage/ice-shared/vip-vvk/data/AOT/psomu3/testing_baseline2/testing_baseline/logs/generation_5

# Execute the Python script with SLURM_ARRAY_TASK_ID as argument. Script also has optional args -i and -o to specify input file and output directory respectively
conda run -n nas --no-capture-output python -u eval.py $SLURM_ARRAY_TASK_ID -i /storage/ice-shared/vip-vvk/data/AOT/psomu3/testing_baseline2/testing_baseline/eval_inputs/eval_input_gen5.csv -o /storage/ice-shared/vip-vvk/data/AOT/psomu3/testing_baseline2/testing_baseline
